creation_rules:
  - path_regex: -test\.env$
    azure_keyvault: https://supafana-test-rg-vault.vault.azure.net/keys/sops-key/72c559d807bb421cb84325bfaa534b71
  - path_regex: -mkdev\.env$
    azure_keyvault: https://supafana-mkdev-vault.vault.azure.net/keys/sops-key/ca3be5c0b9c14439a2b149037133b193
  - path_regex: -prod\.env$
    azure_keyvault: https://supafana-prod-vault.vault.azure.net/keys/sops-key
