using './grafana.bicep'

param supabaseProjectRef = 'kczjrdfrkmmofxkbjxex'
param supabaseServiceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjempyZGZya21tb2Z4a2JqeGV4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxOTk1MTI2OCwiZXhwIjoyMDM1NTI3MjY4fQ.LTisr3-ylpTT79pzTW2t75mT59sB0BV4Cu0ee_XD1WA'
param supafanaDomain = 'supafana-test.com'
