apiVersion: 1

datasources:
- name: prometheus
  datasourceUid: prometheus
  isDefault: true
  type: prometheus
  access: proxy
  url: http://localhost:9090
  jsonData:
    timeInterval: "30s"
    prometheusType: Prometheus
    prometheusVersion: 2.45.0
  manageAlerts: false
  httpMethod: POST
  cacheLevel: 'High'
  incrementalQuerying: true
  incrementalQueryOverlapWindow: 10m
