#!/usr/bin/env sh

set -euo pipefail

orig=`basename $1`
shift

Help()
{
   echo
   echo "Run sql command or open shell to remote database"
   echo
   echo "Syntax: $orig [repl|report <file.sql>|psql <options>]"
   echo
   echo "Commands:"
   echo
   echo "  repl  Open shell to remote db."
   echo "  report <report_file.sql>  Run a report_file.sql and print output in CSV format on stdout."
   echo "  psql <psql options>   Run next command as raw to psql on remote db."
   echo "  help  Print current help."
   echo
   echo "Examples:"
   echo
   echo "  Open psql shell:"
   echo "  > $orig repl"
   echo
   echo "  Run report and save to local csv file:"
   echo "  > $orig report 'reports/stats.sql' > /tmp/stats.csv"
   echo
   echo "  Run psql with option on remote db:"
   echo "  > $orig psql -f 'reports/stats.sql' -F ',' -A > /tmp/stats.csv"
}

Connect()
{
    PASS=$(az account get-access-token --resource-type oss-rdbms --query "[accessToken]" -o tsv)
    ssh -Cfo ExitOnForwardFailure=yes -N -L localhost:$PGPORT:$PGHOST:5432 admin@$APIHOST
    PID=$(pgrep -f "N -L localhost:$PGPORT:")
    trap 'kill $PID' ERR
}

PGUSER=$1
shift
PGHOST="$1.postgres.database.azure.com"
shift
PGDB=$1
shift
APIHOST=$1
shift
PGPORT=$1
shift

if [ $# -ge 1 ]
then
    CMD=${1}
    shift
else
    CMD="help"
fi

case $CMD in
    repl)
        Connect
        PGPASSWORD=$PASS psql -h localhost -p ${PGPORT} -U $PGUSER -d $PGDB -w
        kill $PID
        ;;

    report)
        Connect
        PGPASSWORD=$PASS psql -h localhost -p ${PGPORT} -U $PGUSER -d $PGDB -w -v ON_ERROR_STOP=1 -f "$@" -F "," -A -q --csv -v footer=off
        kill $PID
        ;;

    psql)
        Connect
        PGPASSWORD=$PASS psql -h localhost -p ${PGPORT} -U $PGUSER -d $PGDB -w -v ON_ERROR_STOP=1 "$@"
        kill $PID
        ;;
    *)
        Help >&2
        ;;
esac
