name: Web deploy (test)

on:
  push:
    branches:
      - main
    paths:
      - storefront/**
      - .github/workflows/web-deploy.yml
      - .github/workflows/web-test.yml
jobs:
  deploy_test_web:
    uses: ./.github/workflows/web-deploy.yml
    with:
      env_name: "test"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
