name: Web deploy (mkdev)

on:
  push:
    branches:
      - mkdev-web
    paths:
      - apps/new/**
      - .github/workflows/azure-static-web-apps-stage-deploy.yml

jobs:
  deploy:
    uses: ./.github/workflows/web-deploy.yml
    with:
      env_name: "mkdev"
      AZURE_STATIC_WEB_APPS_STAGE_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_STAGE_API_TOKEN_MKDEV }}
