name: Deploy to Azure Static Web Apps

on:
  workflow_call:
    inputs:
      env_name:
        description: 'Environment name'
        required: true
        type: string
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN:
        required: true

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Build and Deploy Job
    steps:
      - name: Set VITE_APP_VERSION
        run: echo "VITE_APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: 'storefront'
          output_location: 'dist'
          skip_api_build: true
        env:
          PRE_BUILD_COMMAND: npm install -g pnpm@9.5.0
          CUSTOM_BUILD_COMMAND: pnpm install && pnpm run build


  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_STAGE_API_TOKEN }}
          action: "close"
