name: Web deploy (prod)

on:
  push:
    branches:
      - web-prod

jobs:
  deploy_prod_web:
    uses: ./.github/workflows/web-deploy.yml
    with:
      env_name: "prod"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
