name: Web deploy (mkdev)

on:
  push:
    branches:
      - web-mkdev

jobs:
  deploy_mkdev_web:
    uses: ./.github/workflows/web-deploy.yml
    with:
      env_name: "mkdev"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MKDEV }}
